name: Compile and Test

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Rewrite GitHub SSH URLs to HTTPS
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.0.2"
          rebar3-version: "3.24.0"
      - name: Verify OTP
        run: erl -noshell -eval 'io:format("~s~n",[erlang:system_info(otp_release)]), halt().'
      - name: Install mond
        run: cargo install --git https://github.com/benjaminjellis/mond.git --tag 0.0.19 bahn
      - name: Check formatting
        run: bahn format --check
      - name: Build
        run: bahn build
      - name: Test
        run: bahn test
